idf_component_register(
    SRCS
        "main.c"
        "config/runtime_config.c"
        "shared/app_state.c"
        "statemachine/statemachine.c"
        "tasks/console_task.c"
        "tasks/mqtt_task.c"
        "tasks/hardware_task.c"
        "tasks/motor_pid_task.c"
        "tasks/safety_task.c"
        "store/axis_store.c"
    INCLUDE_DIRS
        "."
        "config"
        "shared"
        "statemachine"
        "tasks"
        "store"
    REQUIRES nvs_flash esp_wifi esp_event esp_netif driver
)
