stateDiagram
    mqtt: mqtt_task
    microrl: microrl_task
    sensor_controller: sensor_reader_task
    statemachine: conveyor_job_task
    motor_controller: motor_pid_task
    speed_controller: speed controller
    encoders: quadrature encoder
    sensors: S0/S1 BGS sensors
    motors: MD30C + motor

    mqtt --> statemachine
    statemachine --> mqtt
    microrl --> statemachine
    microrl --> statemachine
    microrl --> motor_controller
    statemachine --> motor_controller
    motor_controller --> motors
    sensor_controller --> statemachine
    sensors --> sensor_controller
    encoder_reader: encoder_reader
    encoders --> encoder_reader
    encoder_reader --> speed_controller
    speed_controller --> motor_controller
    motor_controller --> speed_controller
