#ifndef CONFIG_H
#define CONFIG_H

#define CONVEYOR_ID "C0"

#define CONVEYOR_MQTT_ENABLED 1
#define CONVEYOR_MQTT_STATUS_ENABLED 1

#define CONVEYOR_WIFI_SSID "thrd_warehouse"
#define CONVEYOR_WIFI_PASS "thrd@789"
#define CONVEYOR_MQTT_BROKER_URI "mqtt://192.168.1.126"

#define CONVEYOR_MQTT_TOPIC_CMD "conveyor/C0/cmd"
#define CONVEYOR_MQTT_TOPIC_EMERGENCY "conveyor/C0/emergency"
#define CONVEYOR_MQTT_TOPIC_FEEDBACK "conveyor/C0/feedback"
#define CONVEYOR_MQTT_TOPIC_ALL_EMERGENCY "conveyor/all/emergency"
#define CONVEYOR_MQTT_TOPIC_TRAY "conveyor/C0/tray"

#define CONVEYOR_RUN_PWM 64
#define CONVEYOR_MOTOR_FORWARD_DIRECTION 1

#define CONVEYOR_JOB_TASK_STACK_SIZE 4096
#define CONVEYOR_JOB_TASK_PRIORITY 5
#define CONVEYOR_JOB_QUEUE_LENGTH 8
#define CONVEYOR_JOB_TICK_MS 20
#define CONVEYOR_DONE_HOLD_MS 100

#define CONVEYOR_MQTT_STATUS_TASK_STACK_SIZE 4096
#define CONVEYOR_MQTT_STATUS_TASK_PRIORITY 4
#define CONVEYOR_MQTT_STATUS_PERIOD_MS 100
#define CONVEYOR_MQTT_PAYLOAD_MAX 160

#define CONVEYOR_TIMEOUT_TX_DETECT_MS 5000
#define CONVEYOR_TIMEOUT_TX_CLEAR_MS 5000
#define CONVEYOR_TIMEOUT_RX_DETECT_MS 5000
#define CONVEYOR_TIMEOUT_RX_DONE_MS 5000

#endif
